name: CI

on:
  pull_request:
  schedule:
    # Run daily at 11 AM UTC, after the nightlies are typically published.
    - cron: '0 11 * * *'
  workflow_dispatch:

jobs:
  test:
    name: ci/all_tests.sh (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-26.04
          - macos-26-intel
          - macos-26
          - windows-2025
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Zig
        uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29 # 2.2.1
        with:
          version: 0.16.0
          use-cache: false

      - name: Install Roc
        uses: roc-lang/setup-roc@66d1ae2def87ec77b8670e9ac09c418df2f18c86
        with:
          # Installs the latest nightly from https://github.com/roc-lang/nightlies
          version: nightly-new-compiler

      - name: Run checks
        run: ci/all_tests.sh
